### ISSUE TITLE
Clicking on Date Anchor Links at top of Schedule page doesn't work

### ISSUE THREAD

**Issue by morgansamson** [pycascades/pycascades-cms#53]
Clicking on the date buttons (e.g. `Sunday 19. March`) at the top of the [Schedule page](https://2023.pycascades.com/program/schedule/) does not cause the page to scroll down to the intended anchor.

While inspecting the elements where the actual `Sunday 19. March` section of the schedule began, I couldn't find any tags that had the `#2023-03-19` as an anchor value for the `https://2023.pycascades.com/program/schedule/#2023-03-19` that's generated by clicking the link.

@AetherUnbound said that it might be due to being a component that is in an iframe.

**Comment by AetherUnbound** [comment]
Try as I might, I can't find a way to get this to work! I thought this was iframed but it looks like it's just loaded asynchronously after the page is rendered. This did help me identify some changes I made as part of 9ed03b8eb361fa0c937b3efbbe8bd812d6581877, but I may need to ask the Pretalx folks for a fix here.
